allow defining docker repository
flexkube/calico-helm-chart pull request #5
Opened 2020-11-30 19:04 UTC by ReSearchITEng

due to docker.io (docker hub) limits, setting the repo to a mirror is a must...

2020-11-30 21:07 UTC, invidian requested changes
Thanks for the PR @ReSearchITEng. Changes looks good to me, I'd just adjust the naming so we follow some standards. What do you think?

2020-11-30 21:07 UTC, invidian commented on templates/calico.yaml
> +      - image: {{ .Values.typha.image.repository | default "docker.io" }}/calico/typha:v{{ .Chart.AppVersion }}
I see that Bitnami charts are doing the pattern with `registry`/`repository`/`tag`: https://github.com/bitnami/charts/blob/4ba7e11323e1f787262236cc6707f2f44793d618/bitnami/redis/templates/_helpers.tpl#L67-L88

Perhaps we could do similar, so name a parameter `registry`, we can skip `repository`, `tag` and helper template for now, until it's needed.

2020-11-30 21:07 UTC, invidian commented on templates/calico.yaml
> +      - image: {{ .Values.typha.image.repository | default "docker.io" }}/calico/typha:v{{ .Chart.AppVersion }}
As a side note, if `values.yaml` have default already specified, I think `default "docker.io"` can be skipped here.

2020-11-30 21:47 UTC, ReSearchITEng commented on templates/calico.yaml
> +      - image: {{ .Values.typha.image.repository | default "docker.io" }}/calico/typha:v{{ .Chart.AppVersion }}
resolved.
Just note, my question is: how many different registries should we have?
Now I've set one for typha, and the one from the node is used in all the other 5 places. I guess one for each section is too much :)

2020-11-30 21:47 UTC, ReSearchITEng commented
Just note, my question is: how many different registries should we have?
Now I've set one for typha, and the one from the node is used in all the other 5 places. I guess one for each section is too much :)

2020-12-01 06:34 UTC, invidian commented on templates/calico.yaml
> +      - image: {{ .Values.typha.image.repository | default "docker.io" }}/calico/typha:v{{ .Chart.AppVersion }}
Yeah, I think for now it's fine, thanks!

2020-12-01 06:35 UTC, invidian commented
>Just note, my question is: how many different registries should we have?
Now I've set one for typha, and the one from the node is used in all the other 5 places. I guess one for each section is too much :)

I think it's OK as it is for now. It's simple, fits current needs and is extendable in a non-breaking way.

2020-12-01 06:35 UTC, invidian requested changes
Just last nit, could you please squash the commits?

2020-12-01 09:13 UTC, ReSearchITEng commented
> 
> 
> Just last nit, could you please squash the commits?

Could you use the squash & merge option when you do the merge on your end?

2020-12-01 09:24 UTC, invidian commented
>Could you use the squash & merge option when you do the merge on your end?

I could, though I usually don't do that.

2020-12-01 09:29 UTC, ReSearchITEng commented
> 
> 
> > Could you use the squash & merge option when you do the merge on your end?
> 
> I could, though I usually don't do that.

As they gui does not allow me to do it, I'll have to redo this locallay and make a new PR later on.

2020-12-01 09:41 UTC, invidian commented
@ReSearchITEng you can just use `git rebase` and `git push --force-with-lease` to amend this here. Or did you modify it via GitHub UI? If it's difficult for you, I can handle it then :)

2020-12-01 09:53 UTC, ReSearchITEng commented
> 
> 
> @ReSearchITEng you can just use `git rebase` and `git push --force-with-lease` to amend this here. Or did you modify it via GitHub UI? If it's difficult for you, I can handle it then :)

I can't do it now, I would appreciate if you could handle it this time :)

2020-12-01 10:02 UTC, invidian approved these changes

2020-12-01 10:03 UTC, merged